# Vagrant And Dependent Plugins for KVM

- name: Vagrant Installation
  block:
    - name: VAGRANT - Get Keyring
      ansible.builtin.shell:
        cmd: "wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"
      
    - name: VAGRANT - Add Repo
      ansible.builtin.shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ udist }} main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: VAGRANT - Update & Install package
      ansible.builtin.apt:
        pkg: vagrant
        update_cache: True
      register: vagrant_install

    - name: VAGRANT - libvirt plugin
      ansible.builtin.shell: vagrant plugin install vagrant-libvirt

  always:
    - name: Print Vagrant Version
      block:
        - name: VAGRANT - Check Version
          ansible.builtin.shell: vagrant --version
          register: v_version
        
        - name: VAGRANT - Print Version
          ansible.builtin.debug: 
            var: v_version
      when: ansible_failed_task is not defined

