---
# Tasks to install code editor and markdown editor
# Markdown : Joplin
# Note Taking : Zim
# Terminal Editors: Neovim
# Code Editors: Sublime Text, Vscode

# Joplin - markdown editor
- name: JOPLIN - Install through flatpak
  ansible.builtin.shell: |
    flatpak install -y flathub net.cozic.joplin_desktop
  ignore_errors: True

# Code Editor - Sublime Text
- name: SUBLIME TEXT - Add .gpg key
  ansible.builtin.shell: |
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null
    echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
  ignore_errors: true

# Code Editor - VSCode
- name: VSCODE - Add key and repository
  ansible.builtin.shell: |
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
    sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    rm -f packages.microsoft.gpg
  ignore_errors: true

# Install packages
- name: TEXT EDITORS - Vscode, Sublime text, zim, neovim
  ansible.builtin.apt:
    pkg:
      - "code"
      - "sublime-text"
      - "zim"
      - "neovim"
    state: present
    update_cache: True
  ignore_errors: true
